### PR TITLE
409 radio buttons responsive

### PR DESCRIPTION
**Pull request by ayya-vimala**
This might be the best alternative to https://github.com/BuddhaNexus/buddhanexus-frontend/pull/410 also for Orna.
It makes it responsive in that if the screen width comes under a certain value, you get the dropdown box and otherwise you get the radio buttons. So the behavior is that for a certain screen width it is possible that for the Tibetan you see radio buttons and for the pali you see a dropdown.

### CODE REVIEW

**Comment by sebastian-nehrdich** [comment]
I am testing this on my Laptop with 1440px screen width and I only  see the dropdown menu but not the radio buttons. Maybe there is a bug still happening? I am on the 409-radio-buttons branch...

**Comment by ayya-vimala** [comment]
It depends on the language as well as the size of the screen. If you have a wide screen you see the radio buttons in all languages. If at any given time the screen becomes too small to show the whole header info on one line, it drops the radio buttons and becomes a dropdown. then if the screen becomes even smaller it changes sizes and margins to keep it all on one line. Only somewhere below 900 would you then get 2 lines header again.

**Comment by ayya-vimala** [comment]
The radio buttons disappear at screensize 1380px for Pali, 1280px for Chinese, 1180px for Sanskrit, 1340px for Tibetan and 1480px for multi.
These sizes are calculated based on the table view as this is the biggest header available. We can also change the sizes if you like for a specific language but then you will always get a 2-line header for at least table-view.

**Comment by ayya-vimala** [comment]
For Tibetan and Multi the sizes are rather big for the sole reason that we have the transliteration buttons in the header. If you drop those you can go down to around 1180px too.

**Comment by ayya-vimala** [comment]
On second thought ... I think you have the wrong branch. You need the 409-radio-buttons-responsive branch.

**Review by sebastian-nehrdich — APPROVED** [review]

**Pull request merged**
