### PR TITLE
[155] css slider not working properly

### PR DESCRIPTION
**Pull request by TrebuhD**
@sebastian-nehrdich @ayya-vimala I changed the layout of the filter-box a bit so that every element is on a separate row. It's also now responsive (but not suited for phones yet):

image

image

### CODE REVIEW

**Comment by TrebuhD** [comment]
@ayya-vimala @sebastian-nehrdich I cannot reproduce the issue anymore. Could you check again please? It looks fine on all my browsers.

Chrome:
image

Firefox:
image

**Comment by sebastian-nehrdich** [comment]
> Slider editable box is still slightly too small.
> image

I can confirm that this problem still persists on my machine with chrome (most current google-chrome version with default fonts installed, no zoom active). With firefox, it does not happen. I do not perceive this to be extremely problematic, since only about 1-2 pixels are affected and it only happens when the min. length is abover 100 so once might don't see a huge problem with accepting it. 
Speed is very good, I can see the improvement. If you think it will be difficult to fix the last 2 pixels, I am fine with merging, if not, we can wait a bit longer!

**Comment by TrebuhD** [comment]
@sebastian-nehrdich @ayya-vimala I made a fork of `paper-slider`. It should work now. Please run `npm install` before `npm run dev`.

**Comment by TrebuhD** [comment]
I changed the width of the input to 100px in the paper-slider repository. Please run `npm install` and test again @ayya-vimala.

**Pull request merged**
