### PR TITLE
ST multilingual static texts

### PR DESCRIPTION
**Pull request by ayya-vimala**
I made a few small changes:
1. In neutral-view-multilang: ` This category is currently only available for Sanskrit texts and their Tibetan translations.`
2. In neutral-view-sanskrit: added DSBC and SC as sources.
3. In guidelines- view modes: ` and for those Sanskrit and Tibetan texts where multilingual matches exist.` Because it said that it could only be accessed thought the multilang category which is not true.
4. Added text for info button in mutlilang view.
5. Took out several parts of the code that are not needed for multilingual.

### CODE REVIEW

**Review by sebastian-nehrdich — APPROVED** [review]

**Comment by ayya-vimala** [comment]
This seems to have introduced a bug and needs to be looked at.

**Comment by sebastian-nehrdich** [comment]
> This seems to have introduced a bug and needs to be looked at.

You are right, I am fixing that right now!

**Comment by ayya-vimala** [comment]
Any idea why Travis keeps hanging?

**Comment by sebastian-nehrdich** [comment]
I have no idea what is wrong with travis...

**Comment by ayya-vimala** [comment]
According to instructions here I'm closing the PR and reopening it.
https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

**Pull request merged**
